name: Compile Python Program to EXE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'  # Adjust the Python version as needed

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Compile Python to EXE
        run: |
          pyinstaller --noconsole --onefile --add-data ".\src\Vorlagen\VorlageMonat.docx;." main.py # Adjust the path to your Python script
          Get-ChildItem -Path dist\ -File  # List files in the dist folder

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-program-exe
          path: dist/main.exe  # Path to your compiled EXE file
